//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace escortagram.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class blog_post
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public blog_post()
        {
            this.blog_comment = new HashSet<blog_comment>();
            this.blog_post_to_category = new HashSet<blog_post_to_category>();
            this.blog_related = new HashSet<blog_related>();
            this.blog_tag = new HashSet<blog_tag>();
        }
    
        public int blogId { get; set; }
        public string title { get; set; }
        public string article { get; set; }
        public Nullable<int> authorId { get; set; }
        public Nullable<System.DateTime> date_published { get; set; }
        public string banner_image { get; set; }
        public Nullable<bool> featured { get; set; }
        public Nullable<bool> enabled { get; set; }
        public Nullable<bool> comments_enabled { get; set; }
        public Nullable<int> views { get; set; }
        public Nullable<int> Love { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<blog_comment> blog_comment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<blog_post_to_category> blog_post_to_category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<blog_related> blog_related { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<blog_tag> blog_tag { get; set; }
    }
}
