//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace escortagram.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class blog_comment
    {
        public int comment_id { get; set; }
        public int post_id { get; set; }
        public Nullable<int> is_reply_to_id { get; set; }
        public string comment { get; set; }
        public int user_id { get; set; }
        public Nullable<bool> mark_read { get; set; }
        public Nullable<bool> enabled { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual blog_post blog_post { get; set; }
    }
}
