//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace escortagram.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EscortagramEntities : DbContext
    {
        public EscortagramEntities()
            : base("name=EscortagramEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<UserType> UserTypes { get; set; }
        public virtual DbSet<PageTB> PageTBs { get; set; }
        public virtual DbSet<CountryTb> CountryTbs { get; set; }
        public virtual DbSet<StateTb> StateTbs { get; set; }
        public virtual DbSet<ModelRate> ModelRates { get; set; }
        public virtual DbSet<UserMaster> UserMasters { get; set; }
        public virtual DbSet<ModelImage> ModelImages { get; set; }
        public virtual DbSet<BannerImageTB> BannerImageTBs { get; set; }
        public virtual DbSet<Testimonial> Testimonials { get; set; }
        public virtual DbSet<blog_category> blog_category { get; set; }
        public virtual DbSet<blog_comment> blog_comment { get; set; }
        public virtual DbSet<blog_post> blog_post { get; set; }
        public virtual DbSet<blog_post_to_category> blog_post_to_category { get; set; }
        public virtual DbSet<blog_related> blog_related { get; set; }
        public virtual DbSet<blog_tag> blog_tag { get; set; }
        public virtual DbSet<ModelDetail> ModelDetails { get; set; }
    }
}
