//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace escortagram.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModelImage
    {
        public int ModelImageID { get; set; }
        public Nullable<int> ModelID { get; set; }
        public Nullable<bool> BannerImageGuid { get; set; }
        public string OtherImages { get; set; }
    }
}
