//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace escortagram.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModelRate
    {
        public int RateID { get; set; }
        public Nullable<int> ModelID { get; set; }
        public string Rate30min { get; set; }
        public string Rate1Hour { get; set; }
        public string Rate2Hours { get; set; }
        public string AdditionalHours { get; set; }
        public string DinnerRate { get; set; }
        public string OverNight { get; set; }
    }
}
