//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace escortagram.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModelDetail
    {
        public int ModelID { get; set; }
        public string Description { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<int> MobileNo { get; set; }
        public Nullable<int> Nationality { get; set; }
        public string Languages { get; set; }
        public string Measurements { get; set; }
        public Nullable<int> DressSize { get; set; }
        public Nullable<int> Height { get; set; }
        public string HairColor { get; set; }
        public string EyeColor { get; set; }
        public string Availability { get; set; }
        public string Location { get; set; }
        public string Orientation { get; set; }
        public string FavouritePerfume { get; set; }
        public string FavouriteCuisine { get; set; }
        public Nullable<bool> UKtravel { get; set; }
        public Nullable<bool> WorldWideTravel { get; set; }
        public string Services { get; set; }
    }
}
